CREATE TABLE pcel59krmp1ltqgi.TASK (
	ID BIGINT(20) PRIMARY KEY AUTO_INCREMENT,
    NM_TASK VARCHAR(100) NOT NULL,
    TP_STATUS BIGINT(1) NOT NULL,
    DS_TASK VARCHAR(500),
    DT_CRIACAO DATETIME,
    DT_EDICAO DATETIME,
    DT_CONCLUSAO DATETIME,
    NR_POSITION BIGINT(20)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
